apiVersion: v1
kind: Pod
metadata:
        name: webapp1
        labels:
                app: webapp1

spec:
        containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-queue:release1


